# Generated by Django 2.2.12 on 2022-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
